#include "Seleccioacompanyant.hh"
using namespace std;

Seleccioacompanyant::Seleccioacompanyant(){}

string Seleccioacompanyant::Selecciona(const string& protagonista){
	string dialeg1, secundari;
	bool escollit2 = true; // esta invers
	int x = 1; //	Velocitattext text;
			   //	int x = text.ConsultaVelocitat();
	if (protagonista == "Aleix"){ 						// ALEIX
		cout << "(Bar de la FIB)" << endl << endl;
		sleep (x);
		cout << "<Tuturututu, mira'm soc l'Aleix estic aqui amb la meva vida de palomo de" << endl << "Vilassar de Mar>" << endl << endl;
		sleep (x);
		cout << "Mario: Tio, el curling es millor esport que els escacs" << endl << endl;
		sleep (x);
		cout << "Foskito: Pero que dius? El polo es molt millor que els frisbee golf" << endl << endl;
		sleep (x);
		cout << "Didac: Pero no comparavem escacs i curling?" << endl << endl;
		sleep (x);
		cout << "<Parlant d'esports, jo fa molt que no aposto>" << endl << endl;
		sleep (x);
		cout << "Gabi: Jo vull anar al Wok" << endl << endl;
		sleep (x);
		cout << "Mario: Munchies?" << endl << endl;
		sleep (x);
		cout << "Didac: Qui necessita Wok tenint birra?" << endl << endl;
		sleep (x);
		cout << "Foskito: Tu, sempre igual, sou uns pesaos amb el menjar...";
		sleep (x);
		cout << " Anem al paqui?" << endl << endl;
		sleep (x);
		cout << "Gabi: Tu didac no tens classe?" << endl << endl;
		sleep (x);
		cout << "Didac: Valeeeee" << endl << endl;
		sleep (x);
		cout << "Mario: HSP" << endl << endl;
		sleep (x);
		cout << "Foskito: No, ara en serio. Quin es el millor esport?" << endl << endl;
		sleep (x);
		cout << "Didac: El que es vegi per la tele (tele)*" << endl << endl;
		sleep (x);
		cout << "Gabi: Nah, que va. Maratons de menjar (menjar)*" << endl << endl;
		sleep (x);
		cout << "Didac: Mira, com la mare del Mario" << endl << endl;
		sleep (x);
		cout << "Mario: O com la teva, no ha dit que menja concretament" << endl << endl;
		sleep (x);
		cout << "Foskito: (enfadat) Pero que dieu! Esta clar que el millor esport es anar amb" << endl << "long mentre portes rinyos pel postureo (long)*" << endl << endl;
		sleep (x);
		cout << "Didac: Mario?" << endl << endl;
		sleep (x);
		cout << "<A veure amb quina surt ara>" << endl << endl;
		sleep (x);
		cout << "Mario: (molt segur) Correr's, obviament (correr)*" << endl << endl;
		sleep (x);
		cout << "<No falla>" << endl << endl;
		sleep (x);
		cout << "Didac: Tio sou uns empanats, no es poden tenir discussions series amb vosaltres" << endl << endl;
		sleep (x);
		cout << "Mario: I tu aleix? Que opines?" << endl << endl;
		sleep (x);
		cout << "Aleix: Doncs jo crec que ";
		while (escollit2){
			cin >> dialeg1;
			cout << endl;
			if (dialeg1 == "tele"){
				secundari = "Didac";
				escollit2 = false;
				sleep (x);
				cout << "Foskito, Gabi i Mario: Que?????" << endl << endl;
				sleep (x);
				cout << "Didac: Aha! Us ho he dit" << endl << endl;
				sleep (x);
				cout << "Mario: Pero estas de puta guasa? Com esculls el Didac abans que a mi?" << endl << endl;
				sleep (x);
				cout << "Gabi: Suerte. Com esculls el Didac o el Mario o qualsevol abans que a mi? Jo" << endl << "soc la que te tetes, recordes?" << endl << endl;
				sleep (x);
				cout << "Foskito: Tio, com esculls...? Es igual, es perque soc de Mataro no?" << endl << endl;
				sleep (x);
				cout << "Mario: Primer m'entero de que fumes sense mi, i ara aixo? Ho sento Aleix, haure" << endl << "de reconsiderar la nostra amistat..." << endl << endl;
				sleep (x);
				cout << "Foskito: Doncs si el Mario s'enfada jo no sere menys. M'en vaig a probar rinyos" << endl << "super peques o el que sigui que faig quan no estic a la uni" << endl << endl;
				sleep (x);
				cout << "Gabi: Cuqui, ho sento, pero mai havia vist al Mario tant cabrejat. No entenc" << endl << "com has pogut ser tant cruel com per haver escollit veure la tele... Marxo..." << endl << endl;
				sleep (x);
				cout << "Didac: Doncs si que s'ho han pres malament no?..." << endl << endl;
				sleep (x);
			}
			else if (dialeg1 == "menjar"){
				secundari = "Gabi";
				escollit2 = false;
				sleep (x);
				cout << "Didac, Foskito i Mario: Que?????" << endl << endl;
				sleep (x);
				cout << "<No se de que es sorprenen, com si no fos prou obvi>" << endl << endl;
				sleep (x);
				cout << "Gabi: Sorry bbys, us ho he dit" << endl << endl;
				sleep (x);	
				cout << "Mario: Tio Aleix, pensava que el menjar nomes era per munchies" << endl << endl;
				sleep (x);
				cout << "Foskito: Com pots ser que hagis escollit el menjar puto gordo?" << endl << endl;
				sleep (x);
				cout << "Didac: Es perque te tetes, no hi ha mes" << endl << endl;
				sleep (x);
				cout << "Mario: Doncs jo amb tetes dominaria el mon" << endl << endl;
				sleep (x);
				cout << "Didac: Doncs jo m'haure d'ofendre molt fortament. Tio, com si no t'haguessis" << endl << "possat ja de 'part seva' prou" << endl << endl;
				sleep (x);
				cout << "Foskito: Doncs si el Didac s'ofen jo m'ofenc mes" << endl << endl;
				sleep (x);
				cout << "Mario: Sorry bro, pero si el Didac s'enfada (i el Fokskito ja de pas) m'haure" << endl << "d'indignar molt heavyament" << endl << endl;
				sleep (x);
				cout << "Tots tres: Marxo! Esta clar que tens altres prioritats!" << endl << endl;
				sleep (x);
				cout << "Gabi: Doncs si que s'ho han pres malament no?..." << endl << endl;
				sleep (x);
			}
			else if (dialeg1 == "long"){
				secundari = "Foskito";
				escollit2 = false;
				sleep (x);
				cout << "Didac, Gabi i Mario: Que?????" << endl << endl;
				sleep (x);
				cout << "Foskito: Tomaaaaaa, us ho he dit" << endl << endl;
				sleep (x);
				cout << "Mario: Tio, sabia que tenies mal gust, pero aixo?" << endl << endl;
				sleep (x);
				cout << "Gabi: Jo pensava que el que preferies era montar altres coses, pero ja veig que no..." << endl << endl;
				sleep (x);
				cout << "Didac: Dam, aixo ha estat molt explicit (fins i tot per tu Mario)" << endl << endl;
				sleep (x);
				cout << "Mario: Et puc perdonar moltes coses Aleix, pero que prefereixis el sector" << endl << "masculi de Mataro abans que a mi..." << endl << endl;
				sleep (x);
				cout << "Didac: I que prefereixis long a fer el mandros..." << endl << endl;
				sleep (x);
				cout << "Gabi: Amb qui aniras ara al Macdonalds? Enga, m'en vaig on se m'apreci" << endl << "realment per les meves qualitats i no per l'interes!" << endl << endl;
				sleep (x);
				cout << "Mario: I aixo on es?" << endl << endl;
				sleep (x);
				cout << "Gabi: A l'estanc" << endl << endl;
				sleep (x);
				cout << "Didac: Doncs jo tambe m'en vaig a per tabac" << endl << endl;
				sleep (x);
				cout << "Mario: Doncs jo no em penso quedar sol amb aquests dos, aixo segur" << endl << endl;
				sleep (x);
				cout << "Tots tres: Adeu!" << endl << endl;
				sleep (x);
				cout << "Foskito: Doncs si que s'ho han pres malament no?..." << endl << endl;
				sleep (x);
			}
			else if (dialeg1 == "correr"){
				secundari = "Mario";
				escollit2 = false;
				sleep (x);
				cout << "Didac, Foskito i Gabi: Que?????" << endl << endl;
				sleep (x);
				cout << "Mario: Game over bitches! Us ho he dit!" << endl << endl;
				sleep (x);
				cout << "Gabi: No ho pots dir en serio" << endl << endl;
				sleep (x);
				cout << "Diac: Aleix, per favor, que ens coneixem ja" << endl << endl;
				sleep (x);
				cout << "Foskito: Com es nota que els de vilassar no teniu ni idea de la vida" << endl << endl;
				sleep (x);
				cout << "Didac: I els de Mataro si, no?" << endl << endl;
				sleep (x);
				cout << "Gabi: Calleu, no ens estem enfadant entre nosaltres, ens estem enfadant amb " << endl << "ells" << endl << endl;
				sleep (x);
				cout << "Foskito: Ah, si, es veritat" << endl << endl;
				sleep (x);
				cout << "Didac: Cert" << endl << endl;
				sleep (x);
				cout << "Foskito: Doncs jo no me penso quedar aqui amb gent que no te ni zorra de res" << endl << endl;
				sleep (x);
				cout << "Didac: I jo si no? Valeeee" << endl << endl;
				sleep (x);
				cout << "Gabi: Doncs jo em penso enfadar amb ells mes que vosaltres" << endl << endl;
				sleep (x);
				cout << "Foskito: No, jo mes!" << endl << endl;
				sleep (x);
				cout << "Gabi: Suerte, jo mes!" << endl << endl;
				sleep (x);
				cout << "Didac: A mi me la sua..." << endl << endl;
				sleep (x);
				cout << "Tots tres: Que us petin!" << endl << endl;
				sleep (x);
				cout << "Mario: Doncs si que s'ho han pres malament no?..." << endl << endl;
				sleep (x);
			}
			else if (dialeg1 != "tele" && dialeg1 != "menjar" && dialeg1 != "long" && dialeg1 != "correr") cout << "No s'ha detectat resposta, torna a fer la teva eleccio." << endl << endl;		
		}			
	}
	else if (protagonista == "Mario"){ 					// MARIO 				456!!
		cout << "(Bar de la FIB)" << endl << endl;
		sleep (x);
		cout << "(Notes com el high s'apodera del teu cos)" << endl << endl;
		sleep (x);
		cout << "Unknown: ... sents? " << endl << endl << "Unknown: Mario...? Mario!" << endl << endl;
		sleep (x);
		cout << "<Tio que se t'estant dirijint a tu, digues algo, qualsevol cosa>" << endl << endl;
		sleep (x);
		string comentari;
		cout << "<>";
		cin >> comentari;
		cout << endl;
		sleep (x);
		cout << "<Espera aixo ho he pensat, no ho he dit. A mes vaig tant cec que ni he seguit" << endl << "l'estil grafic per pensar. Merda he de dir algo>" << endl << endl;
		sleep (x);
		cout << "Mario: Pe-perdona, deies?" << endl << endl;
		sleep (x);
		cout << "Gabi: Flexiii :)" << endl << endl;
		sleep (x);
		cout << "Didac: Ets un empanat, parlavem de quin es el millor esport" << endl << endl;
		sleep (x);
		cout << "Foskito: De parlar res, discutim, pero amb vosaltres es com parlar amb una" << endl << "paret..." << endl << endl;
		sleep (x);
		cout << "Aleix: Que, al final, nem al lab de pro?" << endl << endl;
		sleep (x);
		cout << "Tots (menys Foskito): Suuuuerte" << endl << endl;
		sleep (x);
		cout << "Foskito: Veieu?" << endl << endl;
		sleep (x);
		cout << "Gabi: El cas, jo deia que el millor esport son les maratons de menjar (menjar)*" << endl << endl;
		sleep (x);
		cout << "<Com els bons monchis que porto... On dec portar el bocata?>" << endl << endl;
		sleep (x);
		cout << "Didac: Mira, com la mare del Mario" << endl << endl;
		sleep (x);
		cout << "<Si nes menys cec et diria que la teva tambe es passa el dia menjant, pero" << endl << "quina mandra>" << endl << endl;
		sleep (x);
		cout << "Foskito: Dammm, pero igualment t'equivoques. El millor esport es anar amb long" << endl << "i portar rinyos super peques pel postureo (long)*" << endl << endl;
		sleep (x);
		cout << "Didac: No que va, el millor esport es aquell que es miri per la tele (tele)*" << endl << endl;
		sleep (x);
		cout << "Gabi: Cuqui, tu que penses?" << endl << endl;
		sleep (x);
		cout << "Aleix: (molt segur) El millor esport es aquell al que hagis apostat (apostar)*" << endl << endl;
		sleep (x);
		cout << "Foskito: I tu Mario, que n'opines?" << endl << endl;
		sleep (x);
		cout << "<Jo opino que els de Mataro son uns primos..." << endl;
		sleep (x);
		cout << "Espera que s'estant dirigint mi. Rapid, passa de monoleg intern a dialeg extern>" << endl << endl;
		sleep (x);
		cout << "Mario: Doncs jo crec que ";
		sleep (x);
		while (escollit2){
			cin >> dialeg1;
			cout << endl;
			if (dialeg1 == "menjar"){
				secundari == "Gabi";
				escollit2 = false;
				cout << "Aleix, Didac i Foskito: Que?????" << endl << endl;
				sleep (x);
				cout << "Gabi: Ho sabia! Equip flexi!!!" << endl << endl;
				sleep (x);
				cout << "(Intent de choque entre Gabi i Mario, fracasen estrepitosament)" << endl << endl;
				sleep (x);
				cout << "Foskito: Ets un cabron Mario" << endl << endl;
				sleep (x);
				cout << "Gabi: El que pasa es que ens tenen enveja perque no tenen nom d'equip ni salut" << endl << "propi" << endl << endl;
				sleep (x);
				cout << "Didac: Be, tampoc es que sigui tant sorprenent. Com busca el sector femeni..." << endl << endl;
				sleep (x);
				cout << "<Tu calla Didac, fill de putaaa...>" << endl << endl;
				sleep (x);
				cout << "Aleix: Tio, com pots escollir aquesta gorda abans que a mi?" << endl << endl;
				sleep (x);
				cout << "Gabi: Parla, com si tu no fossis un gordo" << endl << endl;
				sleep (x);
				cout << "Aleix: Doncs justament, posats a escollir un gordo que m'esculli a mi" << endl << endl;
				sleep (x);
				cout << "Foskito: Doncs jo fingire que estic molt indignat perque no m'hagi escollit " << endl << "encara que fos obvi des d'un principi que no m'escolliria a mi..." << endl << endl;
				sleep (x);
				cout << "Didac: Jo dire que com pots no escollir algu del llull no perque cregui que " << endl << "aixo es el que hauries de fer sino perque fa molt que no dic res i ja em tocava" << endl << "tenir part en la conversa" << endl << endl;
				sleep (x);
				cout << "Aleix: No, ara en serio Mario. Aqui t'has passat, oblida't de tornar a escalar" << endl << "amb mi" << endl << endl;
				sleep (x);
				cout << "Didac: (en off) Ouuuu, beeeef!" << endl << endl;
				sleep (x);
				cout << "Foskito: Doncs si el de Vilassar s'enfada els de Mataro no serem menys" << endl << endl;
				sleep (x);
				cout << "Gabi: Parla per tu" << endl << endl;
				sleep (x);
				cout << "Didac: Doncs si els 'homes' s'enfaden jo no sere menys" << endl << endl;
				sleep (x);
				cout << "Foskito: Be, ja no tenim res mes a fer per aqui, disfruteu de la vostra" << endl << "'companyia'" << endl << endl;
				sleep (x);
				cout << "Aleix, Didac i Foskito: Adeu!" << endl << endl;
				sleep (x);
				cout << "<Joer, la que s'ha liat. I eso que jo nomes he escollit aquesta opcio pels" << endl << "munchies...>" << endl << endl;
				sleep (x);
				cout << "Gabi: Doncs si que s'ho han pres malament no?" << endl << endl;
				sleep (x);
			}
			else if (dialeg1 == "long"){
				secundari = "Foskito";
				escollit2 = false;
				cout << "Aleix, Didac i Gabi: Que?????" << endl << endl;
				sleep (x);
				cout << "Foskito: Haha! Us foteu, primos!" << endl << endl;
				sleep (x);
				cout << "Tots menys Foskito: No ara en serio. Que? En quin moment se't passa per la ment" << endl << "que la combinacio Mario-Foskito podria ocorrer en la vida real? Moltes ganes de" << endl << "trollejar has de tenir com per escollir aquesta opcio..." << endl << endl;
				sleep (x);
				cout << "Foskito: Tu tio, que passa, que fins i tot m'heu de fer bullying a un joc en el" << endl << "que nomes apareixo per donar mes varietat de personatges?" << endl << endl;
				sleep (x);
				cout << "Tots menys Foskito: Veig que per fi ho comences a pillar, mon ami" << endl << endl;
				sleep (x);
				cout << "Foskito: Eh, neu a la merda, anda" << endl << endl;
				sleep (x);
				cout << "..." << endl << endl;
				sleep (x);
				cout << "..." << endl << endl;
				sleep (x);
				cout << "Mario: Ah, si. (fingint empatia) Nooo, no t'enfadis Foskito, saps que nomes ho" << endl << "diem en conya" << endl << endl;
				sleep (x);
				cout << "Foskito: Te n'adones que soc conscient de que estas fingint empatia perque no" << endl << "soc mes que una creacio de la teva ment i ets tu mateix qui ha escrit lo de " << endl << "'fingint empatia'?" << endl << endl;
				sleep (x);
				cout << "Mario: Calla!" << endl << endl;
				sleep (x);
				cout << "Didac: No ens hauriem d'estar enfadant amb el Mario?" << endl << endl;
				sleep (x);
				cout << "Aleix: Si, pero tu saps lo avorrides que son les classes de pro1 a primera hora" << endl << "del mati, deixa donarli una mica de vidilla a la conversa." << endl << endl;
				sleep (x);
				cout << "Gabi: A mes, enfadarse amb el Mario esta com chungo." << endl << endl;
				sleep (x);
				cout << "Foskito: Tu tio, que si no us enfadeu amb ell la trama no progressa" << endl << "(fastic de restriccio de caracters)" << endl << endl;
				sleep (x);
				cout << "Aleix, Didac i Gabi: (Alhora) Vaaaaale. (Fingint estar enfadats) Tu Mario, com " << endl << "has pogut fer aixo? Com l'has pogut escollir a ell abans que mi?" << endl << endl;
				sleep (x);
				cout << "Didac: Be, si ens hem de posar aixi de conflictius, jo m'en vaig a casa" << endl << endl;
				sleep (x);
				cout << "Gabi: Pero no tens fisica ara?" << endl << endl;
				sleep (x);
				cout << "Didac: He dit (pausa dramatica), a casa. " << endl << endl;
				sleep (x);
				cout << "Aleix: Bueno, jo piro que he d'apostar... digo, currar" << endl << endl;
				sleep (x);
				cout << "Gabi: Doncs jo tambe marxo, ens veiem cuqui <3" << endl << endl;
				sleep (x);
				cout << "<Pero no em deixeu sol amb ell...>" << endl << endl;
				sleep (x);
				cout << "Foskito: Doncs si que s'ho han pres be no?" << endl << endl;
				sleep (x);
			}	
			else if (dialeg1 == "tele"){	
				secundari = "Didac";
				escollit2 = false;
				cout << "Aleix, Gabi i Foskito: Que?????" << endl << endl;
				sleep (x);
				cout << "Didac: Buf, a mi? Segur?" << endl << endl;
				sleep (x);
				cout << "Mario: Calla!" << endl << endl;
				sleep (x);
				cout << "Foskito: Tu, segur que l'has escollit a ell nomes perque es del Llull." << endl << endl;
				sleep (x);
				cout << "Mario: Obviament, que esperaves?" << endl << endl;
				sleep (x);
				cout << "Aleix: Com pot el sentiment del barri eh?" << endl << endl;
				sleep (x);
				cout << "Gabi: Buah, doncs al ritme que portes el joc d'aqui a que l'acabis el Didac ja" << endl << "fara temps que s'haura canviat de carrera i ja s'estara graduant de disseny de" << endl << "videojocs" << endl << endl;
				sleep (x);
				cout << "Didac: Valeeeeee. I tu t'hauras graduat a de la FIB no?" << endl << endl;
				sleep (x);
				cout << "Foskito: Eh, eh, eh. No estem parlant de qui ha deixat quins estudis" << endl << endl;
				sleep (x);
				cout << "Aleix: I tot aixo a que ve?" << endl << endl;
				sleep (x);
				cout << "Gabi: Doncs que esculli el Didac ja no te massa sentit..." << endl << endl;
				sleep (x);
				cout << "Mario: I qualsevol de vosaltres si? Si per quan acabi el joc ja estarem com" << endl << "per tercer de carrera..." << endl << endl;
				sleep (x);
				cout << "Didac: Ni que jo fos la opcio amb menys sentit de les possibles. I no miro a" << endl << "ningu, eh Foskito?" << endl << endl;
				sleep (x);
				cout << "Foskito: Oye vale ya amb el bullying no?" << endl << endl;
				sleep (x);
				cout << "Mario: (ignorant-lo) Oye, per on anavem?" << endl << endl;
				sleep (x);
				cout << "Foskito: Eh! Que estic aqui!" << endl << endl;
				sleep (x);
				cout << "Mario: Si, si. El que diguis" << endl << endl;
				sleep (x);
				cout << "Gabi: Crec que suposadament ens hem d'enfadar amb tu per continuar amb la " << endl << "dinamica del joc"  << endl << endl;
				sleep (x);
				cout << "Aleix: Ah, bueno. Doncs si es per la dinamica s'haura de fer no?" << endl << endl;
				sleep (x);
				cout << "Foskito: Ni que a tu et calguessin escuses per rajar del Mario" << endl << endl;
				sleep (x);
				cout << "Aleix: D'aquest primo? Que va, si ho faig per plaer" << endl << endl;
				sleep (x);
				cout << "Didac: El que fas per plaer son altres coses..." << endl << endl;
				sleep (x);
				cout << "Gabi: Tu no hauries d'estar defensant al Mario?" << endl << endl;
				sleep (x);
				cout << "Didac: Un ha de fer tantes coses..." << endl << endl;
				sleep (x);
				cout << "Foskito: Oye, ens podem enfadar ja amb ell? Que he d'anar a fer un monton de " << endl << "coses com defensar el bronx de la gent sense rinyos" << endl << endl;
				sleep (x);
				cout << "Aleix: Si, si, acabem amb aixo d'una vegada" << endl << endl;
				sleep (x);
				cout << "Gabi: Poh vale. Ets un cuqui molt cuqui :)" << endl << endl;
				sleep (x);
				cout << "Aleix: No tens ni idea de com es fa oi?" << endl << endl;
				sleep (x);
				cout << "Gabi: De fer que?" << endl << endl;
				sleep (x);
				cout << "Aleix: Exacte. Deixam que t'ensenyi. Ets un capullo fill de ta mare que no sap " << endl <<"programar una basura i que a mes sera l'unic que s'amargui prou per acabar la" << endl << "carrera" << endl << endl;
				sleep (x);						
				cout << "Foskito. Wow... Una mica dur no? Jo tenia pensat algo aixi com ets un primo i" << endl << "tal, pero aixo tambe serveix" << endl << endl;
				sleep (x);
				cout << "Gabi: Deixa'm probar. Ets un no cuqui gens cuqui que esta continuament en un" << endl << "intent fallit de no estar trist" << endl << endl;
				sleep (x);
				cout << "Aleix: Be... Es un principi" << endl << endl;
				sleep (x);
				cout << "Aleix, Foskito i Gabi: Enga, que us cundeixi la vida del barrio, que us petin" << endl << endl;
				sleep (x);
				cout << "Didac: No, que li agrada" << endl << endl;
				sleep (x);
				cout << "Tots menys Didac: Calla!" << endl << endl;
				sleep (x);
				cout << "Didac: Doncs si que s'ho han pres malament no? " << endl << endl;
				sleep (x);
			}
			else if (dialeg1 == "apostar"){
				secundari == "Aleix";
				escollit2 = false;
				cout << "Didac, Foskito i Gabi: Que?????" << endl << endl;
				sleep (x);
				cout << "Aleix: Amb el primo em toca?" << endl << endl;
				sleep (x);
				cout << "Mario: Oye que jo m'havia posat d'acord amb tu eh?" << endl << endl;
				sleep (x);
				cout << "<Be, diria. No me'n recordo molt be...>" << endl << endl;
				sleep (x);
				cout << "Foskito: Pero com esculls un primo de Vilassar abans que a mi?" << endl << endl;
				sleep (x);
				cout << "Mario: Escolliria a tots els primos de Vilassar abans" << endl << "que tu. No es que anes a trigar gaire..." << endl << endl;
				sleep (x);
				cout << "Gabi: Cuuuqui, aixo ha estat molt bonic <3" << endl << endl;
				sleep (x);
				cout << "Didac: Crec que es referia al fet de que escolliria a qualsevol persona abans" << endl << "que el Foskito que no pas que escolliria a l'Aleix abans que ningu altre" << endl << endl;
				sleep (x);
				cout << "Mario: Tu sempre tant assertiu Didac" << endl << endl;
				sleep (x);
				cout << "Didac: Pel que calgui" << endl << endl;
				sleep (x);
				cout << "Foskito: Oye loco ya prou no amb el bullying?" << endl << endl;
				sleep (x);
				cout << "<Per que sera que cada cop que intento fer un dialeg on s'enfadin amb mi acaben" << endl << "rajant del Foskito?>" << endl << endl;
				sleep (x);
				cout << "Gabi: Saps que per tu mai hi ha prou :)" << endl << endl;
				sleep (x);
				cout << "Mario: (fentli un sorbo a la birra) That's what she said..." << endl << endl;
				sleep (x);
				cout << "Foskito: Oye en serio, que se suposa que ens estem enfadant amb el Mario" << endl << endl;		
				sleep (x);
				cout << "Didac: Ah, haver-ho dit abans. Aixo si que se'm dona be. Mario, ets un palomo i" << endl << "tothom sap que m'hauries d'haver escollit a mi, encara que jo no volgues anar amb" << endl << "tu des d'un principi" << endl;
				sleep (x);
				cout << "Foskito: Ahi, ahi te veo" << endl;
				sleep (x);
				cout << "Didac: Tu calla" << endl;
				sleep (x);
				cout << "Foskito: ..." << endl;
				sleep (x);
				cout << "Gabi: Cuqui, no vull dir res, pero m'hauries d'haver escollit a mi. Ell es de" << endl << "Vilassar, recordes?" << endl;
				sleep (x);
				cout << "<Be, tu ets de Mataro...>" << endl;
				sleep (x);
				cout << "Mario: ..." << endl;
				sleep (x);
				cout << "Foskito: Aixi esta millor. Com que a mi tampoc m'has escollit jo em sumo a ells i" << endl "marxo d'aqui" << endl;
				sleep (x);
				cout << "Didac, Foskito i Gabi: Adeu!" << endl;
				sleep (x);
				cout << "Aleix: Doncs si que s'ho han pres malament no?" << endl;
				sleep (x);
	
			}
			else if (dialeg1 != "menjar" && dialeg1 != "long" && dialeg1 != "tele" && dialeg1 != "apostar")	cout << "No s'ha detectat resposta, torna a fer la teva eleccio." << endl << endl << "Mario: Doncs jo crec que ";
			sleep (x);
		}
	}
	else if (protagonista == "Gabi"){					// GABI
		cout << "(Bar de la FIB)" << endl;
		sleep (x);
		cout << "<... aleshores si va decidir no acompanyar-lo fins a la parada del bus, per que " << endl << "no para d'intentar allargar la conversa ara?>" << endl;
		sleep (x);
		cout << "Didac: Gabi?" << endl;
		sleep (x);
		cout << "Gabi: (alterada) Que? Que dius?" << endl;
		sleep(1);
		cout << "Didac: Que..." << endl;
		cout << "Gabi: No et sento!" << endl;
		sleep (x);
		cout << "Didac: Que si has decidit ja la teva resposta" << endl;
		sleep (x);
		cout << "Gabi: Que?" << endl;
		sleep (x);
		cout << "Mario: Chupito!" << endl;
		sleep (x);
		cout << "Foskito: Tu tio, no has escoltat res en tota l'estona oi?" << endl;
		sleep (x);
		cout << "Didac: Be, siguem justos. A tu ningu t'ha estat escoltant en tota l'estona" << endl;
		sleep (x);
		cout << "Foskito: Loco, prou amb el bullying a cada possible eleccio no?" << endl;
		sleep (x);
		cout << "Mario: Fins i tot a les no eleccions, la teva ni ha estat programada..." << endl;
		sleep (x);
		cout << "Aleix: Tipic" << endl;
		sleep (x);
		cout << "Didac: (sarcastic) Ou! Aleix, gran aportacio. Mario t'hauras trencat l'esquena" << endl << "pensant que programarli com a dialeg no?" << endl;
		sleep (x);
		cout << "Mario: Calla, que et trec del joc en menys del que has duraras a la uni" << endl;
		sleep (x);
		cout << "(Didac) <I com sap que tinc pensat deixarla?>" << endl;
		sleep (x);
		cout << "(Mario) <Didac, se que es el que estas pensant. A mes, no es que fos algo molt" << endl << "dificil de deduir. I com que se que que pots llegir la meva ment:" << endl << "Cococococococcoooocooooo, Cocoroco co coooooo" << endl;
		sleep (x);
		cout << "(Didac) <Esta imitant una gallina?>" << endl;
		sleep (x);
		cout << "Aleix: ..." << endl;
		sleep (x);
		cout << "Foskito: (a banda) I segueixen ignorantme..." << endl;
		sleep (x);
		cout << "Gabi: No estic pillant res..." << endl;
		sleep (x);
		cout << "Didac: Tranqui, nomes t'has perdut bullying al Foskito i pulles diverses al Mario" << endl;
		sleep (x);
		cout << "Gabi: Ah bueno, lo de sempre no?" << endl; 
		sleep (x);
		cout << "Foskito: Tu tio, ya vale no?" << endl;
		sleep (x);
		cout << "Mario: Ah, i a mes discutiem quin es el millor esport del mon" << endl;
		sleep (x);
		cout << "Didac: Jo dic que el que es vegi per la tele (tele)*" << endl;
		sleep (x);
		cout << "Gabi: Este es de los mios" << endl;
		sleep (x);
		cout << "Foskito: Jo dic que es anar amb long i portar rinyos super peques pel" << endl << "postureo (long)*" << endl;
		sleep (x);
		cout << "Gabi: ..." << endl;
		sleep (x);
		cout << "Mario: Veus per que no et deixo parlar?" << endl;
		sleep (x);
		cout << "Aleix: Jo que aquell al que hagis apostat (apostar)*" << endl;
		sleep (x);
		cout << "Gabi: I tu Mario?" << endl;
		sleep (x);
		cout << "Mario: (molt segur) Correr's obviament (correr)*" << endl;
		sleep (x);
		cout << "Gabi: Oh, vaya" << endl;
		sleep (x);
		cout << "Aleix: I tu koala? Que penses?" << endl;
		sleep (x);
		cout << "< KOLALA <3 >" << endl;
		sleep (x);
		cout << "Gabi: Doncs jo crec que ";
		sleep (x);
		while (escollit2){
			cin >> dialeg1;
			cout << endl;
			if (dialeg1 == "long"){
				escollit2 = false;
				secundari = "Foskito";
				cout << "Aleix, Didac i Mario: Que?????" << endl;
				sleep (x);
				cout << "Foskito: Suuuuuu!" << endl;
				sleep (x);
				cout << "Gabi: Hi ha moltes cosses de mi que no sabeu..." << endl;
				sleep (x);
				cout << "Mario: No, espera. QUE?????" << endl;
				sleep (x);
				cout << "Didac: Podria entendre que pillesis al Mario, pero al Foskito?" << endl;
				sleep (x);
				cout << "Aleix: Ya, ya. Al foskito? En serio?" << endl;
				sleep (x);
				cout << "Foskito: Oye tu, que pasa, que no em pot pillar a mi o que?" << endl;
				sleep (x);
				cout << "Didac: No, no, si ningu esta dient que no pugui..." << endl;
				sleep (x);
				cout << "Foskito: Llavors que?" << endl;
				sleep (x);
				cout << "Aleix: Que ets tu" << endl;
				sleep (x);
				cout << "Mario: :')" << endl;
				sleep (x);
				cout << "Gabi: Eh, que el Foskito no es tant mala opcio..." << endl;
				sleep (x);
				cout << "Didac: Gabi. Que ens coneixem" << endl;
				sleep (x);
				cout << "Foskito: Oye tu pareu ja no? A mes no havieu de fer algu per mantenir la dinamica" << endl << "del joc?" << endl;
				sleep (x);
				cout << "Mario: Be, si. Ens hauriem de enfadar amb la Gabi, pero..." << endl;
				sleep (x);
				cout << "Foskito: Pero?" << endl;
				sleep (x);
				cout << "Aleix: Pero ficar-nos amb tu es mes gracios" << endl;
				sleep (x);
				cout << "Didac: xd lol" << endl;
				sleep (x);
				cout << "Mario: Wow, quina forma de riure mes realista..." << endl;
				sleep (x);
				cout << "Didac: Calla, que ets tu qui m'ha programat" << endl;
				sleep (x);
				cout << "Mario: Si, i et podria haver programat una novia, pero no (risa malvada)" << endl;
				sleep (x);
				cout << "Aleix: Eeeeen fi. Com l'has pogut escollir a ell abans que a mi?" << endl;
				sleep (x);
				cout << "Gabi: Cuqui... No t'enfadis" << endl;
				sleep (x);
				cout << "Didac: Eso, eso. Qui en el seu sa judici escolliria el Foskito? O sigui, em" << endl << "sembla fatal. Aixo no sera algo facil de perdonar" << endl;
				sleep (x);
				cout << "Gabi: Tu tambe?..." << endl;
				sleep (x);
				cout << "Mario: (tothom el mira) Ah, si. (desorientat) Jo tambe m'enfado encara que ara" << endl << "mateix no se ni perque..." << endl;
				sleep (x);
				cout << "Didac: Be, fins que no solventeu les vostres incoherencies alla us quedeu" << endl;
				sleep (x);
				cout << "Aleix, Didac i Mario: Adeu!" << endl;
				sleep (x);
				cout << "Fosktio: Buah, doncs si que s'ho han pres malament no?" << endl;
				sleep (x);
			}
			else if(dialeg1 == "tele"){
				escollit2 = false;
				secundari = "Didac";
				cout << "Aleix, Foskito i Mario: Que?????" << endl;
				sleep (x);
				cout << "Didac: Esa es!" << endl;
				sleep (x);
				cout << "Foskito: Pero estas de conya no?" << endl;
				sleep (x);
				cout << "Mario: Espera... Pensaves que t'escolliria a tu?" << endl;
				sleep (x);
				cout << "Foskito: Que passa que no soc una opcio valida?" << endl;
				sleep (x);
				cout << "Aleix: Doncs... No" << endl;
				sleep (x);
				cout << "Foskito: Tu tio, soc una opcio tant valida com la resta de vosaltres" << endl;
				sleep (x);
				cout << "Didac: Valeee" << endl;
				sleep (x);
				cout << "Mario: Tu calla, que ets a qui ha escollit" << endl;
				sleep (x);
				cout << "Didac: Aix, els gels" << endl;
				sleep (x);
				cout << "Aleix: (amb veu de pena) Pero cuqui... Pensava que teniem algo..." << endl;
				sleep (x);
				cout << "Mario: Buf, tot el xantatge emocional" << endl;
				sleep (x);
				cout << "Gabi: Cuqui..." << endl;
				sleep (x);
				cout << "Foskito: De cuqui, res. On esta l'equip mataro?" << endl;
				sleep (x);
				cout << "Mario: Doncs perdent totes les competicions possibles, pel que es veu" << endl;
				sleep (x);
				cout << "Foskito: Calla. Que consti que estic molt enfadat amb tu Gabi" << endl;
				sleep (x);
				cout << "Gabi: Digali a qui li importi" << endl;
				sleep (x);
				cout << "Mario: No, en serio. Entenc que passis del Foskito, pero de mi? On ha quedat el " << endl << "team flexi?" << endl;
				sleep (x);
				cout << "Gabi: Pero..." << endl;
				sleep (x);
				cout << "Foskito: No no Gabi. Aixo no es soluciona aixi com aixi. Marxem" << endl;
				sleep (x);
				cout << "Mario: Per un cop en ma vida estic d'acord amb tu" << endl;
				sleep (x);
				cout << "Aleix, Foskito i Mario: Adeu!" << endl;
				sleep (x);
				cout << "Didac: Doncs si que s'ho han pres malament no?"<< endl;
				sleep (x);
			}
			else if(dialeg1 == "apostar"){
				escollit2 = false;
				secundari = "Aleix";
				cout << "Didac, Foskito i Mario: (fingint sorpresa) Que?????" << endl;
				sleep (x);
				cout << "Aleix: Koala team!" << endl;
				sleep (x);
				cout << "< KOLALA <3 >" << endl;
				sleep (x);
				cout << "Gabi: Cuqui!!!! :)" << endl;
				sleep (x);
				cout << "Mario: Pero com has pogut escollirlo...? Es igual, deixa-ho" << endl;
				sleep (x);
				cout << "Didac: Ya tia, com has pogut...? Oblida-ho" << endl;
				sleep (x);
				cout << "Foskito: Esque aligual, com el pilles a ell abans que algu de Mataro?" << endl;
				sleep (x);
				cout << "Mario: Tio, que a tu no et pilla ningu" << endl;
				sleep (x);
				cout << "Foskito: Com que no?" << endl;
				sleep (x);
				cout << "Didac: Pues eso, la teva opcio es la pitjor de totes..." << endl;
				sleep (x);
				cout << "Foskito: Neu a la merda, passo de vosaltres" << endl;
				sleep (x);
				cout << "Didac: Doncs tothom passa de tu..." << endl;
				sleep (x);
				cout << "Mario: Man! That burn!" << endl;
				sleep (x);
				cout << "Foskito: Que pessaos, no us havieu d'enfadar amb la gabi per escollir l'Aleix?" << endl;
				sleep (x);
				cout << "Mario: Si, pero hi ha prioritats. Pero canviant de tema, per que l'has escollit a" << endl << "ell?" << endl;
				sleep (x);
				cout << "Foskito: Eso, eso" << endl;
				sleep (x);
				cout << "Didac: Tu calla, que ets el que menys ha durat a la uni" << endl;
				sleep (x);
				cout << "Mario: Com si tu haguessis durat massa mes" << endl;
				sleep (x);
				cout << "Didac: Calla, perds el joc" << endl;
				sleep (x);
				cout << "Mario: Ouch" << endl;
				sleep (x);
				cout << "Gabi: Que zorra!" << endl;
				sleep (x);
				cout << "Didac: No, en serio. Com prefereixes un primo amb cotxe propi, ingressos propis," << endl << "que et dona sexe i... i... Crec que he de reformular la pregunta" << endl;
				sleep (x);
				cout << "Mario: (amb veu de pena) Pero cuqui, pensava que teniem algo. Que l'equip flexi" << endl << "significava algo per tu " << endl;
				sleep (x);
				cout << "Gabi: Cuqui..." << endl;
				sleep (x);
				cout << "Foskito: Be, ja que el Mario li fa xantatge emocinal no sere menys. Pensava que" << endl << "teniem algo els de mataro" << endl;
				sleep (x);
				cout << "Didac: Tu no li importes a ningu" << endl;
				sleep (x);
				cout << "Foskito: QUE T'HAS DE FICAR AMB LA GABI" << endl;
				sleep (x);
				cout << "Didac: (amb veu aguda) Uuuuups!" << endl;
				sleep (x);
				cout << "Foskito: I tu Aleix que cabron, tota l'estona callat sense dir res. Claaaar com" << endl << "t'han escollit" << endl;
				sleep (x);
				cout << "Aleix: Si no parlo es perque el Mario no em programa dialeg..." << endl;
				sleep (x);
				cout << "Didac: Su, su. Escuses. Be nosaltes marxem indignats" << endl;
				sleep (x);
				cout << "Didac, Foskito i Mario: (forcant maximament l'indignacio) Adeu!" << endl;
				sleep (x);
				cout << "Aleix: Doncs si que s'ho han pres malament no?" << endl;
				sleep (x);
			}
			else if(dialeg1 == "correr"){
				escollit2 = false;
				secundari = "Mario";
				cout << "Aleix, Didac i Foskito: Que?????" << endl;
				sleep (x);
				cout << "Mario: I esa! Equipo flexi!" << endl;
				sleep (x);
				cout << "(Intent de choque entre Gabi i Mario, fracasen estrepitosament)" << endl;
				sleep (x);
				cout << "Aleix: Pero Koala, com l'has pogut escollir a ell?" << endl;
				sleep (x);
				cout << "< Kolala :( >" << endl;
				sleep (x);
				cout << "Didac: Ya tio, com has pogut escollir aquest primo abans que a mi? O sigui, ni" << endl << "tolera l'alcohol" << endl;
				sleep (x);
				cout << "Mario: Van ser 12 putos chupitos Didac, la gent normal no els aguanta!" << endl;
				sleep (x);
				cout << "Didac: (burlant-se) Vin sir 12 pitis chipitis Didic, li gint nirmil ni ils" << endl << "iguinti" << endl;
				sleep (x);
				cout << "Mario: Calla, perds el joc" << endl;
				sleep (x);
				cout << "Didac: Zorra" << endl;
				sleep (x);
				cout << "Foskito: Ya ya, o sigui, algu de barna? En serio? Que fas amb te vida tia?" << endl;
				sleep (x);
				cout << "Didac: Foskito, deixa-ho ja. Que a tu ningu et pilla" << endl;
				sleep (x);
				cout << "Foskito: Joer... Que pesaos. Que passa que no puc dir res?" << endl;
				sleep (x);
				cout << "Aleix: Poder si que pots, pero t'ignorarem igual" << endl;
				sleep (x);
				cout << "Didac: On ens fotrem amb tu..." << endl;
				sleep (x);
				cout << "Mario: O ens fotrem amb tot Mataro..." << endl;
				sleep (x);
				cout << "Foskito: ..." << endl;
				sleep (x);
				cout << "Didac: Tu calla Mario que se suposa que ens estem enfadant gradualment amb tu" << endl;
				sleep (x);
				cout << "Mario: Ja ho veig ja..." << endl;
				sleep (x);
				cout << "Aleix: No, en serio. Gabi, aixo m'ha sentat molt malament. Oblida't de que" << endl << "t'acompanyi al Macdo" << endl;
				sleep (x);
				cout << "Gabi: Cuqui..." << endl;
				sleep (x);
				cout << "Didac: Ya. I oblida't d'anar a la ovella amb mi" << endl;
				sleep (x);
				cout << "Gabi: Pero..." << endl;
				sleep (x);
				cout << "Foskito: Si. I oblidat d'anar pel poligon amb mi" << endl;
				sleep (x);
				cout << "Didac: ..." << endl;
				sleep (x);
				cout << "Aleix: ..." << endl;
				sleep (x);
				cout << "Mario: ...." << endl;
				sleep (x);
				cout << "Foskito: Que? Oye, neu a la merda" << endl;
				sleep (x);
				cout << "Didac: (ignorant-lo) Bueno, nosaltres marxem. Us deixem a soles perque seguiu amb" << endl << "les vostres trames" << endl;
				sleep (x);
				cout << "Aleix: Si, pirem. Ale, ya us ho fareu" << endl;
				sleep (x);
				cout << "Foskito: Jo per molt que m'ignorin ni de guasa em quedo amb vosaltres" << endl;
				sleep (x);
				cout << "Aleix, Didac i Foskito: Adeu!" << endl;
				sleep (x);
				cout << "Mario: Doncs si que s'ho han pres malament no?" << endl;
				sleep (x);
				cout << "Gabi: (mirada complice al Mario) Macdo?" << endl;
				sleep (x);
			}
			else if (dialeg1 != "tele" && dialeg1 != "apostar" && dialeg1 != "long" && dialeg1 != "correr") cout << "No s'ha detectat resposta, torna a fer la teva eleccio." << endl << endl;		
		}
	}
	else if (protagonista == "Didac"){
		cout << "(Bar de la FIB)" << endl;
		sleep (x);
		cout << "<Aleshores, si em peto tota la tarda de dimecres i dijous, em donara temps a" << endl << "acabarme la seguent temporada de One Piece?>" << endl;
		sleep (x);
		cout << "Foskito: Tio pero com pots dir aixo? Es que se t'ha anat l'olla?" << endl;
		sleep (x);
		cout << "Mario: Primer. No se m'ha anat l'olla, jo mai n'he tingut. Segon, estas de guasa?" << endl << "Com pot ser el cricket millor que el frisbee golf?" << endl;
		sleep (x);
		cout << "Aleix: A veure esta clar que el karting esta millor que el sumo" << endl;
		sleep (x);
		cout << "Gabi: Com es nota que no sabeu de la vida. Son millor els concursos de chupitos" << endl << "que els recitals de poesia" << endl;
		sleep (x);
		cout << "Didac: Espera espera, de que parlem? I perque estem fent cas al Foskito?" << endl;
		sleep (x);
		cout << "Fosktio: Eh! Que dius matat? A mes, ara que ho penso, no teniu lab de pro?" << endl;
		sleep (x);
		cout << "Aleix, Didac, Gabi i Mario: (A l'unison) Suerteeee" << endl;
		sleep (x);
		cout << "Mario: Parlavem de com perds el joc i tambe de quin es el millor esport del mon" << endl;
		sleep (x);
		cout << "Gabi: Zorra!" << endl;
		sleep (x);
		cout << "<No tenen ni idea de la vida aquests, segur que ni han inclos el hentai>" << endl;
		sleep (x);
		cout << "Didac: Les maratons d'anime les heu descartat ja?" << endl;
		sleep (x);
		cout << "Aleix: Si, just per sotar de repetir per vocacio quatris de la uni" << endl;
		sleep (x);
		cout << "Didac: Mira, com el Mario" << endl;
		sleep (x);
		cout << "Mario: Eh! Que aixo encara no ha passat! No t'avancis als esdeveniments'" << endl;
		sleep (x);
		cout << "Foskito: (Exagerant-ho molt) Loooooool" << endl;
		sleep (x);
		cout << "Mario: A mes, vosaltres dos calleu, que ja veieu quin futur us espera a la uni..." << endl;
		sleep (x);
		cout << "Didac: Per que ho dius?" << endl;
		sleep (x);
		cout << "Mario: Ja veuras ja..." << endl;
		sleep (x);
		cout << "Gabi: Eeeel cas, jo dic que el millor esport del mon son les maratons de menjar" << endl << "(menjar)*" << endl;
		sleep (x);
		cout << "<Es un bon raonament, si>" << endl;
		sleep (x);
		cout << "Aleix: Jo que aquell al que hagis apostat (apostar)*" << endl;
		sleep (x);
		cout << "<Encara que ben pensat...>" << endl;
		sleep (x);
		cout << "Foskito: Que va tios. Esta clar que el millor esport es anar amb long mentre" << endl << "portes rinyos pel postureo (long)*" << endl;
		sleep (x);
		cout << "<Ya esta el primo>" << endl;
		sleep (x);
		cout << "Didac: I tu Mario?" << endl;
		sleep (x);
		cout << "Mario: (Molt segur) Correr's, obviament (correr)*" << endl;
		sleep (x);
		cout << "Didac: L'altre primo" << endl;
		sleep (x);
		cout << "Mario: Eh!" << endl;
		sleep (x);
		cout << "Didac: Ups, ho he dit en veu alta? (sarcastic) Quina llastima..." << endl;
		sleep (x);
		cout << "Mario: Zorra" << endl;
		sleep (x);
		cout << "Gabi: I tu Didac, que penses?" << endl;
		sleep (x);
		cout << "Didac: Doncs jo crec que " << endl;
		sleep (x);
		while (escollit2){
			cin >> dialeg1;
			cout << endl;
			if (dialeg1 == "menjar"){
				escollit2 = false;
				secundari = "Gabi";
				cout << "Aleix, Foskito i Mario: Que?????" << endl;
				sleep (x);
				cout << "Gabi: Aha! Ho sabia!" << endl;
				sleep (x);
				cout << "Foskito: No ho pillo. Entenc que l'haguessis escollit si hagues dit quelcom relacionat amb l'alcohol, pero menjar?" << endl;
				sleep (x);
				cout << "Aleix: Quelcom?" << endl;
				sleep (x);
				cout << "Didac: Escollit?" << endl;
				sleep (x);
				cout << "Mario: (empanat) Menjar?" << endl;
				sleep (x);
				cout << "Gabi: El que us passa es que us moriu d'enveja" << endl;
				sleep (x);
				cout << "Mario: Be, tant com morir... No ens passesim" << endl;
				sleep (x);
				cout << "Aleix: Espera, espera... Quelcom?" << endl;
				sleep (x);
				cout << "Mario: Si Aleix, es una paraula" << endl;
				sleep (x);
				cout << "Aleix: Ho sera per tu..." << endl;
				sleep (x);
				cout << "Foskito: Wait, no ens distreguem de l'important" << endl;
				sleep (x);
			}
			else if (dialeg1 == "apostar"){
				escollit2 = false;
				secundari = "Aleix";
			}
			else if (dialeg1 == "long"){
				escollit2 = false;
				secundari = "Foskito";
			}
			else if (dialeg1 == "correr"){
				escollit2 = false;
				secundari = "Mario";
			}
			else if (dialeg1 != "tele" && dialeg1 != "menjar" && dialeg1 != "long" && dialeg1 != "correr") cout << "No s'ha detectat resposta, torna a fer la teva eleccio." << endl << endl;		
		}
		
	}
	return secundari;
}




